AWSTemplateFormatVersion: "2010-09-09"
Description: >
  This CloudFormation template creates a role assumed by CloudFormation
  during CRUDL operations to mutate resources on behalf of the customer.

Resources:
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      MaxSessionDuration: 8400
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: resources.cloudformation.amazonaws.com
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                aws:SourceAccount:
                  Ref: AWS::AccountId
              StringLike:
                aws:SourceArn:
                  Fn::Sub: arn:${AWS::Partition}:cloudformation:${AWS::Region}:${AWS::AccountId}:type/resource/AWS-ControlTower-LandingZone/*
      Path: "/"
      Policies:
        - PolicyName: ResourceTypePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                - "cloudformation:DescribeOrganizationsAccess"
                - "controltower:CreateLandingZone"
                - "controltower:DeleteLandingZone"
                - "controltower:GetLandingZone"
                - "controltower:GetLandingZoneOperation"
                - "controltower:ListLandingZones"
                - "controltower:ListTagsForResource"
                - "controltower:TagResource"
                - "controltower:UntagResource"
                - "controltower:UpdateLandingZone"
                - "iam:DeleteRole"
                - "iam:DeleteRolePolicy"
                - "iam:DetachRolePolicy"
                - "organizations:AttachPolicy"
                - "organizations:CreateOrganization"
                - "organizations:CreateOrganizationalUnit"
                - "organizations:CreatePolicy"
                - "organizations:DeletePolicy"
                - "organizations:DetachPolicy"
                - "organizations:EnableAWSServiceAccess"
                - "organizations:EnablePolicyType"
                - "organizations:ListRoots"
                - "organizations:UpdatePolicy"
                - "servicecatalog:AssociatePrincipalWithPortfolio"
                - "servicecatalog:AssociateProductWithPortfolio"
                - "servicecatalog:CreatePortfolio"
                - "servicecatalog:CreateProduct"
                - "servicecatalog:CreateProvisioningArtifact"
                - "servicecatalog:DeletePortfolio"
                - "servicecatalog:DeleteProduct"
                - "servicecatalog:DeleteProvisioningArtifact"
                - "servicecatalog:DisassociatePrincipalFromPortfolio"
                - "servicecatalog:DisassociateProductFromPortfolio"
                - "servicecatalog:ListPortfolios"
                - "servicecatalog:ListPrincipalsForPortfolio"
                - "servicecatalog:ListProvisioningArtifacts"
                - "servicecatalog:SearchProductsAsAdmin"
                - "servicecatalog:UpdatePortfolio"
                - "servicecatalog:UpdateProvisioningArtifact"
                - "sso:*"
                Resource: "*"
Outputs:
  ExecutionRoleArn:
    Value:
      Fn::GetAtt: ExecutionRole.Arn
